version: "3.8"
services:
  mongo:
    container_name: mongoserver
    image: mongo:6.0
    ports:
      - 27017:27017
    networks:
      - blog-network
    volumes:
      - mongo-storage:/data/db
  backend:
    container_name: backend-app
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - SECRET_KEY=SecretKey1234
      - DB_CONNECTION=mongodb://mongoserver:27017/db_blog
    networks:
      - blog-network
    depends_on:
      - mongodb
  frontend:
    container_name: frontend-app
    build: ./frontend
    ports:
      - 3000:3000 
    depends_on:
      - mongo

networks:
  blog-network:
    name: blog-network
    
volumes:
  mongo-storage: